### ISSUE TITLE
./ waf operation error

### ISSUE THREAD

**Issue by chenyuanpengcyp** [MTG/essentia-project-template#3]
hello, 
Error when I run ./waf:
Build failed
 -> task in 'essentia_standard_mfcc' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia_standard_fadedetection' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia_standard_onsetrate' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia_standard_beatsmarker' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia_standard_pitchdemo' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia_standard_spectralcontrast' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia_standard_rhythmtransform' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia_standard_vibrato' failed with exit status 1 (run with -v to display more information)

**Comment by alastair** [comment]
This error doesn't make sense. This project template repository has none of these essentia example programs. Perhaps you meant to report the issue in the [main essentia repository](https://github.com/MTG/essentia)?
